'use strict';

const icons = {
 home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',
 search:'<circle cx="10.5" cy="10.5" r="7.5"/><path d="m16 16 5 5"/>',
 map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2zM9 3v16M15 5v16"/>',
 user:'<circle cx="12" cy="7" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2z"/>',
 plus:'<path d="M12 4v16M4 12h16"/>',
 bell:'<path d="M5 10a7 7 0 0 1 14 0v6l2 2H3l2-2zM10 21h4"/>',
 heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8z"/>',
 comment:'<path d="M21 11.5a9 9 0 0 1-9 9 10 10 0 0 1-4-.8L3 21l1.3-5a9 9 0 1 1 16.7-4.5z"/>',
 bookmark:'<path d="M6 3h12v19l-6-4-6 4z"/>',
 share:'<path d="M12 16V3m-4 4 4-4 4 4M7 11H4v10h16V11h-3"/>',
 pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0z"/><circle cx="12" cy="10" r="2.5"/>',
 award:'<circle cx="12" cy="8" r="6"/><path d="m8 13-2 9 6-3 6 3-2-9"/>',
 more:'<circle cx="4" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="20" cy="12" r="1"/>',
 x:'<path d="m6 6 12 12M6 18 18 6"/>',
 back:'<path d="m12 4-8 8 8 8M4 12h17"/>',
 chevron:'<path d="m9 5 7 7-7 7"/>',
 globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v5m10-5v5M3 11h18"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>',
 camera:'<path d="M3 7h4l2-3h6l2 3h4v14H3z"/><circle cx="12" cy="13" r="4"/>',
 navigate:'<path d="m21 3-7 18-3-8-8-3z"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 settings:'<path d="m9 3-1 3-3 1 1 3-2 2 2 2-1 3 3 1 1 3h6l1-3 3-1-1-3 2-2-2-2 1-3-3-1-1-3z"/><circle cx="12" cy="12" r="3"/>',
 filter:'<path d="M3 5h18l-7 8v7l-4 1v-8z"/>',
 flag:'<path d="M5 21V4m0 0h11l-2 4 2 4H5"/>',
 block:'<circle cx="12" cy="12" r="9"/><path d="m5.6 5.6 12.8 12.8"/>',
 shield:'<path d="M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6z"/><path d="m9 12 2 2 4-4"/>',
 doc:'<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v4h4M9 12h6M9 16h6"/>'
};
const {imgs,categories,places,seedPosts}=window.GERARAI_SAMPLE;
const LEGAL=window.GERARAI_LEGAL||{};   // legal pages now come from legal-docs.js (one source); legal.js is no longer loaded
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.pin}</svg>`;}
function decorateIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon);});}
const esc = value => String(value??'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const Store=window.GerarAIStore,CONFIG=window.GERARAI_CONFIG;
let state=Store.load();
let route='feed',feedTab='for-you',profileTab='posts',detailTab='overview',category='all',query='',cityFilter='',map=null,markerLayer=null,tileLayer=null,toastTimer=null,dialogReturnFocus=null;
const main=document.getElementById('main'),dialog=document.getElementById('dialog'),dialogContent=document.getElementById('dialog-content');
/* จุดต่อ (hooks) — live.js แทนที่ฟังก์ชันเหล่านี้เมื่อใช้ Supabase */
function postSource(){return [...state.posts,...seedPosts];}
function isOn(kind,id){return state[kind].includes(id);}
function isFollowing(p){return p.following||state.following.includes(p.author);}
function canEdit(p){return p.own&&String(p.id).startsWith('local-');}
function postBadge(p){return '';}
function meInitial(){return state.profile.name[0]||'B';}
function countSaved(){return state.saved.length;}
function allPosts(){return postSource().map(p=>p.own&&!p.remote?{...p,author:state.profile.name}:p).filter(p=>p.own||(!state.blocked.includes(p.author)&&!state.reported.some(r=>r.id===p.id)));}
function findPost(id){return postSource().find(p=>p.id===id);}
function persist(){const ok=Store.save(state);if(!ok)toast('พื้นที่เก็บข้อมูลเต็ม การเปลี่ยนแปลงครั้งนี้จะอยู่จนกว่าปิดหน้า');return ok;}
function toast(message){const el=document.getElementById('toast');const host=dialog.open?dialog:document.body;if(el.parentElement!==host)host.appendChild(el);el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3500);}
function avatarInner(post){return esc(post.avatar||post.author[0]);}
function avatar(post,cls=''){const demo=post.author==='Mint'&&!post.remote;return `<span class="avatar ${cls}" ${demo?'':`aria-hidden="true"`}>${demo?`<img src="${imgs.bangkok}" alt="">`:avatarInner(post)}</span>`;}
function navMarkup(mobile=false){const items=[['feed','home','หน้าหลัก'],['explore','search','สำรวจ'],['map','map','แผนที่'],['profile','user','โปรไฟล์']];return items.map(([id,ic,label],i)=>`${mobile&&i===2?`<button class="bottom-compose" data-action="compose" aria-label="เพิ่มเรื่องราว">${icon('plus')}</button>`:''}<button class="${mobile?'bottom-item':'nav-item'} ${route.split('?')[0]===id||(route.startsWith('place/')&&id==='map')?'active':''}" data-nav="${id}" ${route.split('?')[0]===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></button>`).join('');}
function renderNav(){document.getElementById('desktop-nav').innerHTML=navMarkup();document.getElementById('bottom-nav').innerHTML=navMarkup(true);document.getElementById('saved-count').textContent=countSaved();document.querySelector('.avatar-header').textContent=meInitial();}
function navigate(path){if(location.hash==='#'+path){route=path;render();}else location.hash=path;}
function goMap(cat='all',city=''){category=cat;cityFilter=city;query='';document.getElementById('search-input').value='';navigate('map');}
function categoryMarkup(selected='all'){return `<div class="category-grid">${categories.map(c=>`<button class="category-chip ${selected===c.id?'active':''}" data-category="${c.id}" aria-pressed="${selected===c.id}"><span class="emoji" aria-hidden="true">${window.GerarAICategoryIcons.render(c.id,c.emoji)}</span>${c.name}</button>`).join('')}</div>`;}
function storiesMarkup(){return `<div class="panel stories"><button class="story" data-action="compose"><span class="story-ring mine">${icon('plus')}</span><small>Your Story</small></button>${[['Bangkok','กรุงเทพฯ',imgs.bangkok],['Chiang Mai','เชียงใหม่',imgs.temple],['Slow Life','ธรรมชาติ',imgs.mountain],['Nimman','นิมมาน',imgs.pharmacy],['Explore','ออกสำรวจ',imgs.temple]].map(([label,city,img])=>`<button class="story" data-story="${city}"><span class="story-ring"><img src="${img}" alt="${city}"></span><small>${label}</small></button>`).join('')}</div>`;}
// M2 Place Disclosure: the card shows only what the Story discloses — venue (link to the place), area (city only, not a
// link) or nothing. The author alone sees that a link is kept private.
function placeChip(p){if(p.areaId&&p.areaLabel)return `<button class="photo-location" data-checkin-area="${esc(p.areaId)}">${icon('pin')}${esc(p.areaLabel)}</button>`;const venue=p.place?(p.placeName||places.find(x=>x.id===p.place)?.name||''):'';if(venue)return `<button class="photo-location" data-place="${esc(p.place)}">${icon('pin')}${esc(venue)}</button>`;if(p.own&&p.ownPlace&&p.placeDisclosure==='private')return `<span class="photo-location photo-location-private" title="ผูกสถานที่ไว้ แต่ไม่แสดงต่อผู้อื่น">${icon('lock')}สถานที่: ส่วนตัว</span>`;return p.city?`<span class="photo-location">${icon('pin')}${esc(p.city)}</span>`:'';}
function postMarkup(p){const liked=isOn('liked',p.id),saved=isOn('saved',p.id),comments=(state.comments[p.id]||[]).length;return `<article class="post-card" data-post="${p.id}"><div class="post-header">${avatar(p)}<button class="post-person" data-person="${p.id}"><strong>${esc(p.author)}</strong><small>${p.location?esc(p.location)+' · ':''}${esc(p.time)}${p.edited?' · แก้ไขแล้ว':''}</small></button>${postBadge(p)}<button class="icon-button" data-action="post-more" data-id="${p.id}" aria-label="ตัวเลือกเรื่องราว">${icon('more')}</button></div>${p.image?`<div class="photo-wrap"><img class="post-photo" src="${esc(p.image)}" alt="${esc(window.GerarAICheckinRead.heading(p))}" loading="lazy">${placeChip(p)}<span class="image-count">1 / 1</span></div>`:''}<div class="post-copy">${p.title?`<h2>${esc(p.title)}</h2>`:''}<p>${esc(p.body)}</p><div class="tags">${p.tags.map(t=>`<button class="tag" data-query="${esc(t)}">#${esc(t)}</button>`).join('')}</div></div><div class="post-actions"><button class="action ${liked?'liked':''}" data-action="like" data-id="${p.id}" aria-label="ถูกใจเรื่องราว" aria-pressed="${liked}">${icon('heart')}<span>${p.likes+(liked?1:0)}</span></button><button class="action" data-action="comments" data-id="${p.id}" aria-label="ความคิดเห็น">${icon('comment')}<span>${p.comments+comments}</span></button><button class="action" data-action="share-post" data-id="${p.id}" aria-label="แชร์ลิงก์เรื่องราว">${icon('share')}</button><button class="action bookmark ${saved?'saved':''}" data-action="save" data-id="${p.id}" aria-label="บันทึกเรื่องราว" aria-pressed="${saved}">${icon('bookmark')}</button></div></article>`;}
function levelMarkup(){return `<div class="adventure-card character-rank-card"><div class="level-line"><span class="explorer-icon" aria-hidden="true">🧭</span><div><strong>Lv. 1 <span style="color:#528b55">Wanderer</span></strong><p>นักเดินทาง · เรื่องราวของคุณเพิ่งเริ่มต้น</p></div></div><button class="text-button class-path-link" data-action="class-paths">ดูเส้นทางอาชีพทั้งหมด</button><p class="form-help character-rank-note">โหมดต้นแบบยังไม่คำนวณ XP หรือปลดล็อกอาชีพ</p></div>`;}
function badgesMarkup(profile=false){const badges=[['🏅','First Trip'],['🌙','Night Owl'],['🍜','Food Lover'],['🌲','Nature Fan'],['🧭','10 Countries']];return `<div class="mini-badges demo-badges"><span class="sample-chip" title="เหรียญตัวอย่างในโหมดต้นแบบ ไม่ได้มาจากกิจกรรมจริง">ตัวอย่าง</span>${badges.map(([e,t])=>profile?`<div class="badge-cell"><button data-action="badges" aria-label="เหรียญ ${t}">${e}</button><small>${t}</small></div>`:`<button class="mini-badge" data-action="badges" aria-label="เหรียญ ${t}">${e}</button>`).join('')}</div>`;}
function rightRail(){return `<aside class="right-rail"><section><div class="rail-head"><h2>การผจญภัยของคุณ</h2><button data-nav="profile">ดูโปรไฟล์</button></div>${levelMarkup()}${badgesMarkup()}</section><section class="panel rail-section"><div class="rail-head"><h2>เมืองที่น่าออกไปเจอ <span class="sample-chip">ตัวอย่าง</span></h2><button data-nav="explore">ดูทั้งหมด</button></div>${[['เชียงใหม่',imgs.temple,'วัด คาเฟ่ และขุนเขา'],['กรุงเทพฯ',imgs.bangkok,'เรื่องราวทุกมุมเมือง'],['นิมมาน',imgs.pharmacy,'เดินเล่นในย่านคุ้นเคย']].map(([name,img,sub])=>`<button class="destination-row" data-city="${name}"><img src="${img}" alt=""><span><strong>${name}</strong><small>${sub}</small></span>${icon('chevron')}</button>`).join('')}</section><div class="quote-card"><p>โลกกว้างรอให้เรา<br>ออกไปเจอ<small>REAL PLACES. REAL PEOPLE. REAL STORIES.</small></p></div><p class="demo-note">พื้นที่ทดลอง GERARAI · บุคคล สถานที่ รีวิว และตัวเลขเป็นข้อมูลตัวอย่าง ภาพประกอบสร้างด้วย AI</p></aside>`;}
function feedPosts(){return allPosts().filter(p=>feedTab==='following'?isFollowing(p):feedTab==='nearby'?p.city==='เชียงใหม่':feedTab==='world'?false:true);}
function empty(title,body,button=''){return `<div class="empty-state">${icon('globe')}<h2>${title}</h2><p>${body}</p>${button}</div>`;}
function renderFeed(){main.innerHTML=`<div class="feed-page"><div class="page-heading"><div><h1>เรื่องราวระหว่างทาง <span class="vd-compass" aria-hidden="true"></span></h1><p>ชีวิตจริง · สถานที่จริง · ผู้คนจริง · เรื่องราวจริง</p></div><span class="date-note">ให้ความอยากรู้นำทางวันนี้</span></div><div class="feed-layout"><section class="feed-column">${storiesMarkup()}<div class="feed-tabs" role="tablist" aria-label="เลือกฟีด">${[['for-you','สำหรับคุณ'],['following','กำลังติดตาม'],['nearby','ใกล้ฉัน'],['world','ต่างประเทศ']].map(([id,name])=>`<button class="tab ${feedTab===id?'active':''}" role="tab" aria-selected="${feedTab===id}" data-feed-tab="${id}">${name}</button>`).join('')}</div>${feedTab==='nearby'?'<p class="search-result-note">พื้นที่ตัวอย่าง: เชียงใหม่</p>':''}<div id="feed-posts">${feedPosts().map(postMarkup).join('')||empty('เรื่องราวใหม่กำลังรอคุณ','ต้นแบบนี้มีเรื่องราวในประเทศไทย ลองสำรวจเมืองที่มีอยู่ก่อนได้เลย',`<button class="primary" data-nav="explore">สำรวจสถานที่</button>`)}</div></section>${rightRail()}</div><section class="category-section"><h2 class="section-title">หมวดหมู่สถานที่ยอดนิยม</h2>${categoryMarkup()}</section></div>`;}
function filteredPlaces(){const q=query.trim().toLowerCase();return places.filter(p=>(category==='all'||category===p.category)&&(!cityFilter||p.city.includes(cityFilter)||p.name.includes(cityFilter))&&(!q||[p.name,p.city,p.description,categories.find(c=>c.id===p.category).name].join(' ').toLowerCase().includes(q)));}
function placeCard(p){return `<button class="place-list-card" data-place="${esc(p.id)}">${p.image?`<img src="${esc(p.image)}" alt="ภาพประกอบ ${esc(p.name)}" loading="lazy">`:`<span class="place-list-noimg" aria-hidden="true">${window.GerarAICategoryIcons.render(p.category,(categories.find(c=>c.id===p.category)||{}).emoji||'📍')}</span>`}<div class="place-list-copy"><h3>${esc(p.name)}</h3><p>${esc(p.city)}, ${p.country&&p.country!=='TH'?esc(p.country):'Thailand'}</p>${p.is_sample===false?'<div class="place-source">สถานที่ใน GERARAI</div>':`<div class="rating">★ ${p.rating}<span>(${p.reviews} รีวิวตัวอย่าง)</span></div>`}<span class="place-type">${categories.find(c=>c.id===p.category).name}</span></div></button>`;}
function renderExplore(){const matches=filteredPlaces(),postMatches=query&&!window.GerarAIRemote?.enabled?allPosts().filter(p=>[p.title,p.body,p.city,...p.tags].join(' ').toLowerCase().includes(query.toLowerCase())):[];main.innerHTML=`<div class="explore-page">${query?`<div class="page-heading"><div><h1>ผลการค้นหา “${esc(query)}”</h1><p>ค้นพบมุมใหม่จากเรื่องราวและสถานที่</p></div><button class="secondary" data-action="clear-search">ล้าง</button></div>`:`<div class="discovery-banner"><small>EXPLORE MORE. REAL LIFE.</small><h1>วันนี้ อยากไปเจออะไร?</h1><p>เริ่มจากเมืองที่ชอบ แล้วให้เรื่องราวพาไป</p></div>`}<section class="category-section"><h2 class="section-title">ออกสำรวจในแบบของคุณ</h2>${categoryMarkup(category)}</section><h2 class="section-title">${cityFilter?esc(cityFilter):'สถานที่น่าค้นพบ'}${places.some(x=>x.is_sample!==false)?' <span class="sample-badge">ข้อมูลตัวอย่าง</span>':''}</h2><div class="explore-grid">${matches.map(placeCard).join('')}</div>${!matches.length?empty('ยังไม่พบสถานที่','ลองเปลี่ยนคำค้นหรือเลือกหมวดทั้งหมด'):''}${postMatches.length?`<h2 class="section-title" style="margin-top:26px">เรื่องราวที่เกี่ยวข้อง</h2><div class="saved-layout">${postMatches.map(postMarkup).join('')}</div>`:''}</div>`;}
function renderMap(){const matches=filteredPlaces();main.innerHTML=`<section class="map-page"><div class="page-heading"><div><h1>แผนที่การผจญภัย</h1><p>ทุกหมุดมีเรื่องราว · เลือกหมุดหรือการ์ดเพื่อรู้จักสถานที่</p></div><button class="secondary" data-action="reset-map">${icon('globe')}ดูทั้งหมด</button></div><div class="map-layout"><div class="map-panel"><div id="map" class="map-canvas" aria-label="แผนที่สถานที่ตัวอย่างในประเทศไทย"></div><div class="map-top">${categoryMarkup(category)}</div><span class="map-status">พิกัดและรีวิวตัวอย่าง</span><div class="map-hint">${query?'ค้นหา “'+esc(query)+'” · ':''}${cityFilter?'พื้นที่: '+esc(cityFilter):'ประเทศไทย'} · ${matches.length} สถานที่${query||cityFilter?` <button class="hint-clear" data-action="reset-map">ล้างตัวกรอง</button>`:''}</div></div><section class="map-list"><div class="map-list-head"><h2>${query?'ผลการค้นหา “'+esc(query)+'”':esc(cityFilter)||'ค้นพบรอบตัวคุณ'}</h2><p>${matches.length} สถานที่ในต้นแบบ</p></div>${matches.map(placeCard).join('')||empty('ยังไม่พบสถานที่','ลองเลือกหมวดอื่น')}</section></div></section>`;initMap(matches);}
function initMap(matches){if(!window.L){mapFallback('แผนที่ยังโหลดไม่สำเร็จ ลองเลือกสถานที่จากรายการด้านล่าง');return;}map=L.map('map',{zoomControl:true,scrollWheelZoom:true}).setView([16.3,99.9],6);tileLayer=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors'}).addTo(map);let tilesLoaded=0,failed=0;tileLayer.on('tileload',()=>{tilesLoaded++;document.querySelector('.map-offline')?.remove();});tileLayer.on('tileerror',()=>{failed++;if(failed>3&&!tilesLoaded)mapFallback('โหลดพื้นแผนที่ไม่ได้ ตรวจการเชื่อมต่ออินเทอร์เน็ต หรือเลือกสถานที่จากรายการ');});markerLayer=L.layerGroup().addTo(map);matches.forEach(p=>{const cat=categories.find(c=>c.id===p.category);const marker=L.marker(p.coords,{title:p.name,alt:p.name,icon:L.divIcon({className:'custom-map-marker',html:`<span class="map-pin" style="background:${cat.color}"><b>${window.GerarAICategoryIcons.render(cat.id,cat.emoji)}</b></span>`,iconSize:[42,46],iconAnchor:[20,42]})});marker.bindPopup(`<strong>${esc(p.name)}</strong><br>${esc(p.city)}${p.is_sample?' · ข้อมูลตัวอย่าง':''}<br><button data-place="${esc(p.id)}">ดูสถานที่และเรื่องราว</button>`);marker.addTo(markerLayer);});if(matches.length===1)map.setView(matches[0].coords,13);else if(matches.length>1)map.fitBounds(matches.map(p=>p.coords),{padding:[55,130],maxZoom:12});setTimeout(()=>map?.invalidateSize(),100);}
function mapFallback(message){const panel=document.querySelector('.map-panel');if(panel&&!panel.querySelector('.map-offline')){const el=document.createElement('div');el.className='map-offline';el.innerHTML=`${esc(message)}<button class="secondary" data-action="retry-map">ลองโหลดใหม่</button>`;panel.append(el);}}
function detailBody(p){if(detailTab==='stories')return `<h2 class="section-title">เรื่องราวจากผู้ใช้</h2>${allPosts().filter(x=>x.place===p.id).map(postMarkup).join('')||empty('ยังไม่มีเรื่องราว','เป็นคนแรกที่บันทึกความทรงจำจากที่นี่',`<button class="primary" data-action="compose" data-place-id="${p.id}">แชร์เรื่องราว</button>`)}`;if(detailTab==='reviews'&&p.is_sample===false)return `<h2 class="section-title">รีวิว</h2><p>ยังไม่มีรีวิวจากสมาชิก</p>`;if(detailTab==='reviews')return `<h2 class="section-title">★ ${p.rating} <span class="muted">จาก ${p.reviews} รีวิวตัวอย่าง</span></h2><p>คะแนนและจำนวนรีวิวใช้ประกอบการออกแบบเท่านั้น ยังไม่มีรีวิวจากผู้ใช้งานจริง</p><div class="notification-item"><strong>Beam · ★★★★★</strong><p>บรรยากาศน่าแวะ เหมาะกับการเดินสำรวจย่านนี้ต่อ</p><small>รีวิวสมมติสำหรับทดลองหน้าจอ</small></div>`;if(detailTab==='info')return `<h2 class="section-title">ข้อมูลสถานที่</h2><p>${esc(p.description)}</p><div class="info-row">${icon('pin')}${esc(p.address)}</div><div class="info-row">${icon('clock')}${esc(p.hours)}</div>${p.is_sample===false?'':'<p class="form-help" style="margin-top:18px">สถานที่นี้เป็นข้อมูลทดลอง ไม่ใช่ข้อมูลร้านที่ยืนยันแล้ว</p>'}`;if(detailTab==='nearby')return `<div class="explore-grid">${places.filter(x=>x.city===p.city&&x.id!==p.id).slice(0,3).map(placeCard).join('')}</div>`;if(!p.image)return `<p>${esc(p.description)}</p>`;return `<p>${esc(p.description)}</p><div class="gallery">${[p.image,p.image,p.image].map((src,i)=>`<button data-action="gallery" data-id="${p.id}" aria-label="เปิดภาพประกอบสถานที่ ${i+1}"><img src="${src}" alt="ภาพประกอบ ${p.name}"></button>`).join('')}</div>`;}
function renderPlace(id){const p=places.find(x=>x.id===id);if(!p){main.innerHTML=empty('ไม่พบสถานที่','กลับไปสำรวจสถานที่อื่นได้',`<button class="primary" data-nav="map">เปิดแผนที่</button>`);return;}const saved=isOn('savedPlaces',id);main.innerHTML=`<div class="detail-wrap"><button class="back-link" data-nav="map">${icon('back')}กลับไปแผนที่</button><div class="detail-hero${p.image?'':' detail-hero-noimg'}">${p.image?`<img src="${esc(p.image)}" alt="ภาพประกอบ ${esc(p.name)}">`:`<span class="detail-hero-icon" aria-hidden="true">${window.GerarAICategoryIcons.render(p.category,(categories.find(c=>c.id===p.category)||{}).emoji||'📍')}</span>`}<div class="detail-hero-tools"><button class="icon-button" data-action="share-place" data-id="${id}" aria-label="แชร์สถานที่">${icon('share')}</button><button class="icon-button ${saved?'saved':''}" data-action="save-place" data-id="${id}" aria-label="บันทึกสถานที่" aria-pressed="${saved}">${icon('bookmark')}</button></div></div><div class="detail-summary"><div class="place-heading"><div class="place-icon">${window.GerarAICategoryIcons.render(p.category,categories.find(c=>c.id===p.category).emoji)}</div><div class="place-text"><h1>${esc(p.name)}</h1>${p.is_sample===false?'<div class="place-source">สถานที่ใน GERARAI</div>':`<div class="rating">★ ${p.rating}<span>(${p.reviews} รีวิวตัวอย่าง)</span></div>`}<p class="muted">${categories.find(c=>c.id===p.category).name} · ${esc(p.city)}, Thailand</p></div><button class="primary" data-action="directions" data-id="${id}">${icon('navigate')}นำทาง</button></div><div class="detail-tabs" role="tablist" aria-label="รายละเอียดสถานที่">${[['overview','ภาพรวม'],['stories','เรื่องราว'],['reviews','รีวิว'],['info','ข้อมูล'],['nearby','ใกล้เคียง']].map(([key,name])=>`<button class="tab ${detailTab===key?'active':''}" role="tab" aria-selected="${detailTab===key}" data-detail-tab="${key}">${name}</button>`).join('')}</div><div class="detail-body">${detailBody(p)}</div></div>${detailTab==='overview'?`<div class="detail-grid"><section><h2 class="section-title">เรื่องราวจากผู้ใช้</h2>${allPosts().filter(x=>x.place===id).map(postMarkup).join('')||empty('ยังไม่มีเรื่องราว','ลองเพิ่มเรื่องราวแรกของสถานที่นี้',`<button class="primary" data-action="compose" data-place-id="${id}">แชร์เรื่องราว</button>`)}</section><aside class="panel info-card"><h2 class="section-title">แวะมาทำความรู้จัก</h2><div class="info-row">${icon('pin')}${esc(p.address)}</div><div class="info-row">${icon('clock')}${esc(p.hours)}</div><p class="form-help" style="margin-top:18px">ข้อมูลและพิกัดสมมติสำหรับต้นแบบ</p></aside></div>`:''}</div>`;}
function profilePhotos(){const posts=allPosts().filter(p=>p.own&&p.image);return `<div class="photo-grid">${posts.map(p=>`<button class="photo-tile" data-action="open-post" data-id="${p.id}"><img src="${esc(p.image)}" alt="${esc(window.GerarAICheckinRead.heading(p))}"><span>${esc(p.title)}</span></button>`).join('')}${[places[1],places[0]].map(p=>`<button class="photo-tile" data-place="${p.id}"><img src="${p.image}" alt="${p.name}"><span>${p.city}</span></button>`).join('')}</div>`;}
function renderProfile(){main.innerHTML=`<div class="profile-wrap"><div class="profile-cover"><span class="cover-caption">EXPLORE<br>MORE.<br>REAL LIFE.</span></div><section class="profile-card"><div class="profile-topline"><div class="avatar profile-avatar">${esc(state.profile.name[0])}</div><div class="profile-buttons"><button class="secondary" data-action="safety" aria-label="ความเป็นส่วนตัวและความปลอดภัย">${icon('shield')}<span>ความปลอดภัย</span></button><button class="secondary" data-action="edit-profile">${icon('settings')}แก้ไขโปรไฟล์</button></div></div><h1 class="profile-name">${esc(state.profile.name)}<span class="verified" aria-label="เครื่องหมายตัวอย่าง">✓</span></h1><p class="profile-handle">@baitoeyy · โปรไฟล์ทดลอง</p><p class="profile-bio">${esc(state.profile.bio).replace(/\n/g,'<br>')}</p><div class="profile-meta"><span>${icon('pin')}Thailand</span><span>${icon('calendar')}1998</span><span>${icon('globe')}9 ประเทศ</span></div><div class="profile-stats"><div><b>1.2K</b><small>ผู้ติดตาม</small></div><div><b>${356+state.following.length}</b><small>กำลังติดตาม</small></div><div><b>87</b><small>สถานที่ที่ไป</small></div><div><b>42</b><small>เมือง</small></div></div><div class="profile-achievements">${levelMarkup()}${badgesMarkup(true)}</div></section><div class="profile-tabs" role="tablist" aria-label="เนื้อหาโปรไฟล์">${[['posts','โพสต์'],['visited','แผนที่ชีวิต'],['places','สถานที่'],['album','อัลบั้ม'],['saved','บันทึก']].map(([key,name])=>`<button class="tab ${profileTab===key?'active':''}" role="tab" aria-selected="${profileTab===key}" data-profile-tab="${key}">${name}</button>`).join('')}</div><div id="profile-content">${profileTab==='posts'||profileTab==='album'?profilePhotos():profileTab==='saved'?`<div class="saved-layout">${savedMarkup()}</div>`:profileTab==='places'?`<div class="explore-grid">${places.some(p=>isOn('savedPlaces',p.id))?places.filter(p=>isOn('savedPlaces',p.id)).map(placeCard).join(''):places.slice(0,3).map(placeCard).join('')}</div>`:`<div class="panel rail-section"><h2 class="section-title">ทุกที่ที่ไป คือส่วนหนึ่งของเรา</h2><p class="form-help">เส้นทางตัวอย่าง: กรุงเทพฯ → เชียงใหม่</p><div class="explore-grid">${[places[1],places[2]].map(placeCard).join('')}</div><button class="primary" data-nav="map">เปิดแผนที่การผจญภัย</button></div>`}</div></div>`;}
function savedMarkup(){const saved=allPosts().filter(p=>isOn('saved',p.id));return saved.length?saved.map(postMarkup).join(''):empty('เก็บเรื่องราวที่อยากกลับมาดู','กดรูปที่คั่นหนังสือใต้โพสต์ แล้วเรื่องราวจะอยู่ตรงนี้',`<button class="primary" data-nav="feed">ไปที่ฟีดเรื่องราว</button>`);}
function renderSaved(){main.innerHTML=`<div class="page-heading"><div><h1>เรื่องราวที่บันทึกไว้</h1><p>มุมโปรดสำหรับวันถัดไป</p></div></div><div class="saved-layout">${savedMarkup()}</div>`;}
function render(){if(map){map.remove();map=null;}renderNav();if(route==='feed')renderFeed();else if((route==='map'||route.startsWith('map?')))renderMap();else if(route==='explore')renderExplore();else if(route==='profile')renderProfile();else if(route==='saved')renderSaved();else if(route==='privacy'||route==='terms')renderLegal(route);else if(route.startsWith('place/'))renderPlace(route.split('/')[1]);else if(route.startsWith('post/')){const p=allPosts().find(p=>p.id===route.split('/')[1]);main.innerHTML=`<div class="saved-layout"><button class="back-link" data-nav="feed">${icon('back')}กลับไปเรื่องราว</button>${p?postMarkup(p):empty('ไม่พบเรื่องราว','เรื่องราวที่สร้างในต้นแบบจะอยู่เฉพาะเบราว์เซอร์ที่บันทึกไว้')}</div>`;}else{route='feed';renderFeed();}decorateIcons(main);}
function openDialog(title,body){dialogReturnFocus=document.activeElement;document.getElementById('dialog-title').textContent=title;dialogContent.innerHTML=body;decorateIcons(dialogContent);if(!dialog.open)dialog.showModal();}
function closeDialog(){dialog.close();dialogReturnFocus?.focus?.();}
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
function compose(placeId=''){openDialog('วันนี้คุณเจออะไร?',`<form id="compose-form"><p class="form-help">เรื่องราวทดลองนี้เก็บเฉพาะบนเบราว์เซอร์ของคุณ ยังไม่เผยแพร่ให้คนอื่นเห็น</p><label class="form-field">หัวข้อเรื่องราว<input name="title" required maxlength="100" placeholder="ตั้งชื่อให้ความทรงจำวันนี้"></label><label class="form-field">เล่าเรื่องของคุณ<textarea name="body" required maxlength="2000" placeholder="สถานที่ ผู้คน หรือเรื่องเล็ก ๆ ที่ทำให้วันนี้พิเศษ…"></textarea></label><label class="form-field">สถานที่<select name="place">${places.map(p=>`<option value="${p.id}" ${p.id===placeId?'selected':''}>${p.name} · ${p.city}</option>`).join('')}</select></label><label class="photo-upload">${icon('camera')}<input id="post-photo-input" type="file" accept="image/png,image/jpeg,image/webp" aria-label="แนบภาพเรื่องราว"></label><p class="form-help">ภาพ PNG, JPG หรือ WebP ไม่เกิน 15 MB · ระบบย่อภาพให้อัตโนมัติ · ไม่แนบภาพก็ได้</p><div id="photo-preview"></div><div class="form-submit"><button class="secondary" type="button" data-action="close-dialog">ยกเลิก</button><button class="primary" type="submit">บันทึกเรื่องราวทดลอง</button></div></form>`);window.GerarAIDiscoveryUI.mount(document.getElementById('compose-form'));let photo='';const input=document.getElementById('post-photo-input');input.addEventListener('change',async()=>{const file=input.files[0];photo='';document.getElementById('photo-preview').innerHTML='';if(!file)return;const submit=document.querySelector('#compose-form [type=submit]');submit.disabled=true;try{const img=await Store.prepareImage(file);photo=img.dataUrl;document.getElementById('photo-preview').innerHTML=`<img class="compose-preview" src="${photo}" alt="ภาพที่เลือก"><p class="form-help">ย่อภาพเป็น ${img.width}×${img.height} px (~${Math.round(img.bytes/1024)} KB) ก่อนบันทึก</p>`;}catch(err){input.value='';toast(err.message==='decode'?'เปิดไฟล์ภาพนี้ไม่ได้ ลองเลือกภาพอื่น':'เลือกภาพ PNG, JPG หรือ WebP ขนาดไม่เกิน 15 MB');}finally{submit.disabled=false;}});document.getElementById('compose-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target),title=String(data.get('title')).trim(),body=String(data.get('body')).trim();if(!title||!body){toast('กรอกหัวข้อและเรื่องราวก่อนบันทึก');return;}let discovery;try{discovery=window.GerarAIDiscoveryUI.read(e.target);}catch(err){toast(err.message);return;}const p=places.find(p=>p.id===data.get('place'));state.posts.unshift({id:'local-'+Date.now(),author:state.profile.name,avatar:state.profile.name[0],city:p.city,location:p.city+', Thailand',time:'เมื่อสักครู่',place:p.id,image:photo,title,body,tags:['MyAdventure'],likes:0,comments:0,following:false,own:true,discovery});const saved=persist();closeDialog();feedTab='for-you';navigate('feed');toast(saved?'บันทึกเรื่องราวไว้บนเครื่องนี้แล้ว':'เพิ่มเรื่องราวแล้ว แต่พื้นที่เก็บข้อมูลเต็ม');});}
function comments(id){const p=allPosts().find(p=>p.id===id);if(!p)return;openDialog('ความคิดเห็น',`<p class="form-help">ความคิดเห็นใหม่เก็บบนเครื่องนี้เท่านั้น</p><div class="comment-list">${p.comments?`<div class="comment-row"><span class="avatar">J</span><p><strong>June · ความคิดเห็นตัวอย่าง</strong>บรรยากาศดีมาก อยากลองออกไปสำรวจบ้าง ✨</p></div>`:''}${(state.comments[id]||[]).map(c=>`<div class="comment-row"><span class="avatar">${esc(state.profile.name[0])}</span><p><strong>${esc(state.profile.name)}</strong>${esc(c)}</p></div>`).join('')}</div><form id="comment-form" class="comment-form"><input name="comment" aria-label="เขียนความคิดเห็น" placeholder="เขียนความคิดเห็น…" required maxlength="500"><button class="primary" type="submit">ส่ง</button></form>`);document.getElementById('comment-form').addEventListener('submit',e=>{e.preventDefault();const value=new FormData(e.target).get('comment').trim();if(!value)return;state.comments[id]??=[];state.comments[id].push(value);persist();comments(id);refreshPost(id);});}
function refreshPost(id){const el=main.querySelector(`[data-post="${id}"]`),p=allPosts().find(x=>x.id===id);if(el&&p)el.outerHTML=postMarkup(p);renderNav();}
async function shareLink(path){const url=new URL(location.href);url.hash=path;try{if(location.protocol==='file:')throw Error('local');await navigator.clipboard.writeText(url.href);toast('คัดลอกลิงก์แล้ว ลิงก์บนเครื่องเปิดได้เฉพาะเครื่องนี้');}catch{openDialog('ลิงก์สำหรับเปิดในเครื่อง',`<p class="form-help">ต้นแบบนี้ยังไม่ออนไลน์ ลิงก์นี้ใช้กับเครื่องที่เปิดเว็บอยู่เท่านั้น</p><label class="form-field">ลิงก์<input value="${esc(url.href)}" readonly onclick="this.select()"></label>`);}}
function showStory(city){const p=city==='กรุงเทพฯ'?places[1]:city==='นิมมาน'?places[0]:city==='ธรรมชาติ'?places[4]:places[2];openDialog(city,`<div class="story-dialog"><img src="${p.image}" alt="ภาพประกอบ ${city}"><p>${esc(p.description)}</p><button class="primary" data-place="${p.id}">สำรวจสถานที่นี้</button></div>`);}
function badgesDialog(){openDialog('เหรียญแห่งการเดินทาง',`<p class="form-help"><span class="sample-chip">ตัวอย่าง</span> เหรียญและเลเวลในโหมดต้นแบบเป็นข้อมูลตัวอย่าง ในโหมดสมาชิกเหรียญคำนวณจาก Discovery จริงบนเซิร์ฟเวอร์</p><div class="badge-grid">${[['🏅','First Trip','ก้าวแรกของการเดินทาง'],['🌙','Night Owl','ออกสำรวจยามค่ำคืน'],['🍜','Food Lover','ตามหารสชาติใหม่'],['🌲','Nature Fan','กลับไปหาธรรมชาติ'],['🧭','10 Countries','เดินทางข้ามพรมแดน'],['📸','Story Teller','บันทึกเรื่องราวดี ๆ']].map(([e,t,d])=>`<div class="badge-item"><span>${e}</span><b>${t}</b><small>${d}</small></div>`).join('')}</div>`);}
function editProfile(){openDialog('ตัวละครของฉัน',`<form id="profile-form"><p class="form-help">การเปลี่ยนแปลงจะบันทึกไว้ในเบราว์เซอร์นี้</p><label class="form-field">ชื่อในโลก GERARAI<input name="name" required maxlength="40" value="${esc(state.profile.name)}"></label><label class="form-field">แนะนำตัว<textarea name="bio" maxlength="220">${esc(state.profile.bio)}</textarea></label><div class="form-submit"><button class="primary" type="submit">บันทึก</button></div></form>`);document.getElementById('profile-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target),name=d.get('name').trim();if(!name)return;state.profile={name,bio:d.get('bio').trim()};persist();closeDialog();render();toast('บันทึกโปรไฟล์ทดลองแล้ว');});}
function search(q){query=q.trim();category='all';cityFilter='';document.getElementById('search-input').value=query;navigate('explore');}
/* ---------- ความน่าเชื่อถือ: แก้ไข / รายงาน / บล็อก (ระยะ 4, โหมด local) ---------- */
const REPORT_REASONS=[['spam','สแปมหรือโฆษณา'],['inappropriate','เนื้อหาไม่เหมาะสม'],['harassment','คุกคามหรือกลั่นแกล้ง'],['privacy','เปิดเผยข้อมูลส่วนตัวของผู้อื่น'],['false','ข้อมูลสถานที่ไม่จริงหรือทำให้เข้าใจผิด'],['other','อื่น ๆ']];
function editPost(id){const p=state.posts.find(x=>x.id===id);if(!p)return;openDialog('แก้ไขเรื่องราว',`<form id="edit-form"><label class="form-field">หัวข้อเรื่องราว<input name="title" required maxlength="100" value="${esc(p.title)}"></label><label class="form-field">เล่าเรื่องของคุณ<textarea name="body" required maxlength="2000">${esc(p.body)}</textarea></label><label class="form-field">สถานที่<select name="place">${places.map(x=>`<option value="${esc(x.id)}" ${x.id===p.place?'selected':''}>${esc(x.name)} · ${esc(x.city)}</option>`).join('')}</select></label><div class="form-submit"><button class="secondary" type="button" data-action="close-dialog">ยกเลิก</button><button class="primary" type="submit">บันทึกการแก้ไข</button></div></form>`);
 window.GerarAIDiscoveryUI.mount(document.getElementById('edit-form'),p.discovery);document.getElementById('edit-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target),title=String(d.get('title')).trim(),body=String(d.get('body')).trim();if(!title||!body){toast('กรอกหัวข้อและเรื่องราวก่อนบันทึก');return;}let discovery;try{discovery=window.GerarAIDiscoveryUI.read(e.target);}catch(err){toast(err.message);return;}const place=places.find(x=>x.id===d.get('place'));Object.assign(p,{title,body,place:place?.id||'',city:place?.city||'',location:place?place.city+', Thailand':'GERARAI',edited:true,discovery});persist();closeDialog();render();toast('บันทึกการแก้ไขแล้ว');});}
function reportPost(id){const p=findPost(id);if(!p)return;openDialog('รายงานเรื่องราว',`<form id="report-form"><p class="form-help">บอกเราว่าเรื่องราวของ ${esc(p.author)} มีปัญหาอะไร เราจะซ่อนเรื่องราวนี้จากฟีดของคุณทันที<br><b>ต้นแบบ:</b> รายงานเก็บบนเครื่องนี้เท่านั้น ยังไม่ถึงทีมดูแลจริง</p><fieldset class="reason-list"><legend class="sr-only">เหตุผล</legend>${REPORT_REASONS.map(([v,t],i)=>`<label class="reason"><input type="radio" name="reason" value="${v}" ${i===0?'required':''}><span>${t}</span></label>`).join('')}</fieldset><label class="form-field">รายละเอียดเพิ่มเติม (ไม่บังคับ)<textarea name="note" maxlength="300" placeholder="ช่วยให้ทีมดูแลเข้าใจปัญหาได้เร็วขึ้น"></textarea></label><div class="form-submit"><button class="secondary" type="button" data-action="close-dialog">ยกเลิก</button><button class="primary" type="submit">ส่งรายงาน</button></div></form>`);
 document.getElementById('report-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);if(!d.get('reason')){toast('เลือกเหตุผลก่อนส่งรายงาน');return;}state.reported.push({id,reason:d.get('reason'),note:String(d.get('note')||'').trim(),at:new Date().toISOString()});state.saved=state.saved.filter(x=>x!==id);persist();closeDialog();if(route==='post/'+id)navigate('feed');else render();toast('ขอบคุณที่รายงาน เราซ่อนเรื่องราวนี้จากฟีดของคุณแล้ว');});}
function confirmBlock(id){const p=findPost(id);if(!p||p.own)return;openDialog(`บล็อก ${p.author}?`,`<p class="form-help">คุณจะไม่เห็นเรื่องราวของ ${esc(p.author)} ในฟีด การค้นหา และหน้าสถานที่ และจะเลิกติดตามโดยอัตโนมัติ<br>เลิกบล็อกได้ทุกเมื่อที่ โปรไฟล์ → ความปลอดภัย</p><div class="form-submit"><button class="secondary" data-action="close-dialog">ยกเลิก</button><button class="primary danger-fill" data-action="confirm-block" data-id="${esc(id)}">บล็อก</button></div>`);}
function blockAuthor(name){if(!state.blocked.includes(name))state.blocked.push(name);state.following=state.following.filter(x=>x!==name);const hidden=seedPosts.filter(p=>p.author===name).map(p=>p.id);state.saved=state.saved.filter(x=>!hidden.includes(x));persist();closeDialog();if(route.startsWith('post/'))navigate('feed');else render();toast(`บล็อก ${name} แล้ว`);}
function safetyDialog(){openDialog('ความเป็นส่วนตัวและความปลอดภัย',`<h3 class="dialog-section">ผู้ใช้ที่บล็อก</h3>${state.blocked.length?state.blocked.map(n=>`<div class="safety-row"><span class="avatar">${esc(n[0])}</span><strong>${esc(n)}</strong><button class="secondary" data-action="unblock" data-name="${esc(n)}">เลิกบล็อก</button></div>`).join(''):'<p class="form-help">ยังไม่ได้บล็อกใคร</p>'}<h3 class="dialog-section">เรื่องราวที่รายงาน</h3>${state.reported.length?`<div class="safety-row"><span>ซ่อนไว้ ${state.reported.length} เรื่องราว</span><button class="secondary" data-action="unreport-all">แสดงอีกครั้ง</button></div>`:'<p class="form-help">ยังไม่มีรายงาน</p>'}<h3 class="dialog-section">ข้อมูลของคุณ</h3><p class="form-help">ในต้นแบบนี้ ข้อมูลทั้งหมดอยู่ในเบราว์เซอร์นี้เท่านั้น ไม่มีการส่งออกไปที่ใด</p><div class="legal-buttons"><a class="secondary" href="#privacy">${icon('doc')}นโยบายความเป็นส่วนตัว</a><a class="secondary" href="#terms">${icon('doc')}ข้อกำหนดการใช้งาน</a></div><button class="text-button danger" data-action="reset-local">ล้างข้อมูลทดลองบนเครื่องนี้</button>`);}

/* ---------- นโยบายความเป็นส่วนตัว / ข้อกำหนด (ร่าง) ---------- */
function renderLegal(kind){const doc=LEGAL[kind];if(!doc){main.innerHTML='<p class="empty-state" role="status">กำลังโหลดเอกสาร…</p>';return;}main.innerHTML=`<article class="legal-page"><button class="back-link" data-nav="profile">${icon('back')}กลับ</button><div class="draft-banner"><strong>ฉบับร่างสำหรับต้นแบบ</strong> ยังไม่ผ่านการตรวจจากนักกฎหมาย และยังไม่มีผลบังคับใช้ ข้อความใน [วงเล็บเหลี่ยม] คือจุดที่เจ้าของโปรเจกต์ต้องตัดสินใจหรือกรอกก่อนเปิดให้สมัครสมาชิก</div><h1>${doc.title}</h1><p class="muted">ปรับปรุงล่าสุด: [วันที่เผยแพร่]</p>${doc.sections.map(([h,body])=>`<section><h2>${h}</h2>${body}</section>`).join('')}<p class="legal-switch"><a href="#${kind==='privacy'?'terms':'privacy'}">${kind==='privacy'?'อ่านข้อกำหนดการใช้งาน':'อ่านนโยบายความเป็นส่วนตัว'} →</a></p></article>`;}
document.getElementById('global-search').addEventListener('submit',e=>{e.preventDefault();search(document.getElementById('search-input').value);});
const WRITE_ACTIONS=new Set(['compose','like','save','save-place','follow','comments','report','block','edit-profile','edit-post','delete-post','confirm-delete','confirm-block','safety']);
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-nav]');if(!b)return;
 /* โหมดสมาชิกแต่ live.js ไม่ทำงาน (ไฟล์หาย/โหลดไม่ครบ) → ห้ามตกไปใช้ flow ต้นแบบ */
 if(CONFIG.backend==='supabase'&&!window.GERARAI_LIVE&&WRITE_ACTIONS.has(b.dataset.action)){openDialog('ระบบสมาชิกโหลดไม่ครบ','<p class="form-help">ไฟล์ของระบบสมาชิก (live.js / remote.js) โหลดไม่สำเร็จ ลองรีเฟรชหน้า (Ctrl+F5) หรือตรวจว่าเปิดเว็บจากโฟลเดอร์เวอร์ชันล่าสุด</p>');return;}
 if(b.dataset.nav){if(dialog.open)closeDialog();if(b.dataset.nav==='explore'){query='';category='all';cityFilter='';}navigate(b.dataset.nav);return;}
 if(b.dataset.place){if(dialog.open)closeDialog();detailTab='overview';navigate('place/'+b.dataset.place);return;}
 if(b.dataset.category){category=b.dataset.category;if(route==='explore'||(route==='map'||route.startsWith('map?')))render();else{cityFilter='';query='';navigate('map');}return;}
 if(b.dataset.feedTab){feedTab=b.dataset.feedTab;renderFeed();return;}
 if(b.dataset.detailTab){detailTab=b.dataset.detailTab;renderPlace(route.split('/')[1]);return;}
 if(b.dataset.profileTab){profileTab=b.dataset.profileTab;renderProfile();return;}
 if(b.dataset.query){search(b.dataset.query);return;}
 if(b.dataset.city){goMap('all',b.dataset.city==='นิมมาน'?'เชียงใหม่':b.dataset.city);return;}
 if(b.dataset.story){showStory(b.dataset.story);return;}
 if(b.dataset.person){const p=allPosts().find(p=>p.id===b.dataset.person);if(p.own){navigate('profile');return;}const followed=isFollowing(p);openDialog(p.author,`<div class="level-line">${avatar(p)}<div><strong>${p.author}</strong><p class="form-help">${p.location} · โปรไฟล์ตัวอย่าง</p></div></div><p class="form-help" style="margin-top:20px">เก็บเรื่องราวดี ๆ จากทุกการเดินทาง</p><div class="form-submit" style="justify-content:flex-start"><button class="primary" data-action="follow" data-id="${p.id}">${followed?'กำลังติดตาม':'ติดตาม'}</button><button class="secondary" data-action="block" data-id="${p.id}">บล็อก</button></div>`);return;}
 const action=b.dataset.action,id=b.dataset.id;
 if(action==='close-dialog')closeDialog();
 else if(action==='compose')compose(b.dataset.placeId);
 else if(action==='like'){state.liked=state.liked.includes(id)?state.liked.filter(x=>x!==id):[...state.liked,id];persist();refreshPost(id);}
 else if(action==='save'){state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];persist();if(route==='saved'||(route==='profile'&&profileTab==='saved'))render();else refreshPost(id);toast(state.saved.includes(id)?'บันทึกเรื่องราวแล้ว':'นำออกจากรายการบันทึกแล้ว');}
 else if(action==='comments')comments(id);
 else if(action==='share-post')shareLink('post/'+id);
 else if(action==='share-place')shareLink('place/'+id);
 else if(action==='open-post')navigate('post/'+id);
 else if(action==='save-place'){state.savedPlaces=state.savedPlaces.includes(id)?state.savedPlaces.filter(x=>x!==id):[...state.savedPlaces,id];persist();renderPlace(id);toast(state.savedPlaces.includes(id)?'บันทึกสถานที่ในโปรไฟล์แล้ว':'นำสถานที่ออกจากรายการแล้ว');}
 else if(action==='gallery'){const p=places.find(x=>x.id===id);openDialog(p.name,`<div class="story-dialog"><img src="${p.image}" alt="${p.name}"><p class="form-help">ภาพประกอบสถานที่ตัวอย่าง สร้างด้วย AI</p></div>`);}
 else if(action==='directions'){const p=places.find(x=>x.id===id);openDialog('ดูพิกัดตัวอย่าง',`<p class="form-help">พิกัดนี้ใช้ทดลองหน้าจอ ไม่ใช่ตำแหน่งร้านที่ยืนยันแล้ว ลิงก์จะเปิด Google Maps ในแท็บใหม่</p><p>${p.name}</p><div class="form-submit"><a class="primary" href="https://www.google.com/maps/search/?api=1&query=${p.coords[0]},${p.coords[1]}" target="_blank" rel="noopener noreferrer">เปิดแผนที่ภายนอก</a></div>`);}
 else if(action==='class-paths')openDialog('เส้นทางอาชีพ',window.GerarAICharacter?.pathDialogMarkup([])||'<p>Wanderer Lv.1</p>');
 else if(action==='badges')badgesDialog();
 else if(action==='edit-profile')editProfile();
 else if(action==='notifications')openDialog('การแจ้งเตือน',`<p class="form-help">ตัวอย่างการแจ้งเตือน ยังไม่เชื่อมต่อสมาชิกจริง</p><div class="notification-item">🏅 ยินดีต้อนรับสู่การผจญภัยครั้งใหม่<br>ลองสำรวจแผนที่ แล้วบันทึกสถานที่ที่ชอบ<small>ตัวอย่างกิจกรรม</small></div><div class="notification-item">✨ เริ่มต้นเรื่องราวของคุณได้แล้ววันนี้<small>รูปภาพหนึ่งใบ อาจพาใครสักคนออกเดินทาง</small></div>`);
 else if(action==='about')openDialog('GERARAI · v0.5.1 · โหมดต้นแบบ',`<p class="form-help">ต้นแบบทดลองจากภาพอ้างอิงของคุณ</p><p style="font-size:.9rem;line-height:1.9">ฟีด แผนที่ สถานที่ และโปรไฟล์เชื่อมถึงกัน กดถูกใจ บันทึก แสดงความคิดเห็น และสร้างเรื่องราวได้ โดยเก็บข้อมูลเฉพาะเบราว์เซอร์นี้<br><br>ชื่อบุคคล ร้าน รีวิว พิกัด และตัวเลขเป็นข้อมูลตัวอย่าง ภาพประกอบสร้างด้วย AI ยังไม่มีระบบสมาชิกหรือโพสต์สาธารณะ</p><p class="legal-links"><a href="#privacy">นโยบายความเป็นส่วนตัว (ร่าง)</a> · <a href="#terms">ข้อกำหนดการใช้งาน (ร่าง)</a></p>`);
 else if(action==='search-dialog'){openDialog('ค้นหาเรื่องราวและสถานที่',`<form id="mobile-search-form"><label class="form-field">คำค้น<input type="search" name="q" placeholder="เช่น เชียงใหม่ คาเฟ่ หรือเยาวราช" value="${esc(query)}" autofocus></label><div class="form-submit"><button class="primary" type="submit">ค้นหา</button></div></form>`);document.getElementById('mobile-search-form').addEventListener('submit',e=>{e.preventDefault();const q=new FormData(e.target).get('q');closeDialog();search(q);});}
 else if(action==='clear-search'){query='';cityFilter='';category='all';document.getElementById('search-input').value='';renderExplore();}
 else if(action==='reset-map'){category='all';query='';cityFilter='';render();}
 else if(action==='retry-map')render();
 else if(action==='follow'){const p=allPosts().find(p=>p.id===id);if(p.following){toast('คุณติดตามโปรไฟล์ตัวอย่างนี้อยู่แล้ว');return;}state.following=state.following.includes(p.author)?state.following.filter(x=>x!==p.author):[...state.following,p.author];persist();closeDialog();toast(state.following.includes(p.author)?'ติดตามในต้นแบบแล้ว':'เลิกติดตามในต้นแบบแล้ว');}
 else if(action==='edit-post')editPost(id);
 else if(action==='report')reportPost(id);
 else if(action==='block')confirmBlock(id);
 else if(action==='confirm-block'){const p=findPost(id);blockAuthor(p.author);}
 else if(action==='unblock'){state.blocked=state.blocked.filter(x=>x!==b.dataset.name);persist();safetyDialog();render();toast('เลิกบล็อกแล้ว');}
 else if(action==='unreport-all'){state.reported=[];persist();safetyDialog();render();toast('แสดงเรื่องราวที่รายงานไว้อีกครั้งแล้ว');}
 else if(action==='safety')safetyDialog();
 else if(action==='reset-local')openDialog('ล้างข้อมูลทดลองบนเครื่องนี้?',`<p class="form-help">เรื่องราว ความคิดเห็น รายการบันทึก การบล็อก และโปรไฟล์ที่แก้ไว้ในเบราว์เซอร์นี้จะหายทั้งหมด ย้อนกลับไม่ได้</p><div class="form-submit"><button class="secondary" data-action="close-dialog">ยกเลิก</button><button class="primary danger-fill" data-action="confirm-reset-local">ล้างข้อมูล</button></div>`);
 else if(action==='confirm-reset-local'){Store.reset();state=Store.freshState();persist();closeDialog();navigate('feed');render();toast('ล้างข้อมูลทดลองแล้ว');}
 else if(action==='post-more'){const p=allPosts().find(p=>p.id===id);openDialog('ตัวเลือกเรื่องราว',`<button class="side-link" data-action="share-post" data-id="${id}">${icon('share')}คัดลอกลิงก์</button><button class="side-link" data-place="${p.place}">${icon('pin')}ดูสถานที่ในเรื่องราว</button>${canEdit(p)?`<button class="side-link" data-action="edit-post" data-id="${id}">${icon('settings')}แก้ไขเรื่องราว</button><button class="side-link danger" data-action="delete-post" data-id="${id}">${icon('x')}ลบเรื่องราว</button>`:p.own?'<p class="form-help">โพสต์ตัวอย่างของโปรไฟล์ทดลอง แก้ไขหรือลบไม่ได้</p>':`<button class="side-link" data-action="report" data-id="${id}">${icon('flag')}รายงานเรื่องราวนี้</button><button class="side-link danger" data-action="block" data-id="${id}">${icon('block')}บล็อก ${esc(p.author)}</button>`}`);}
 else if(action==='delete-post'){openDialog('ลบเรื่องราวนี้?',`<p class="form-help">เรื่องราวนี้จะถูกลบออกจากเบราว์เซอร์ของคุณ</p><div class="form-submit"><button class="secondary" data-action="close-dialog">ยกเลิก</button><button class="primary" data-action="confirm-delete" data-id="${id}">ลบเรื่องราว</button></div>`);}
 else if(action==='confirm-delete'){state.posts=state.posts.filter(p=>p.id!==id);state.saved=state.saved.filter(x=>x!==id);state.liked=state.liked.filter(x=>x!==id);delete state.comments[id];persist();closeDialog();render();toast('ลบเรื่องราวแล้ว');}
});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!dialog.open){e.preventDefault();if(innerWidth>700)document.getElementById('search-input').focus();else document.querySelector('.mobile-search').click();}});
window.addEventListener('hashchange',()=>{if(dialog.open)dialog.close();route=location.hash.slice(1)||'feed';render();window.scrollTo({top:0,behavior:'instant'});});
/* แสดงเวอร์ชันและโหมดให้เห็นชัด เพื่อไม่สับสนกับไฟล์รุ่นเก่า */
const APP_VERSION='v0.7.0-dev';document.querySelector('.sidebar-bottom small').textContent=`GERARAI © 2026 · ${APP_VERSION} · ${CONFIG.backend==='local'?'โหมดต้นแบบออฟไลน์':'ระบบสมาชิก'}`;
if(CONFIG.backend==='local'){const u=new URL(location.href);u.searchParams.delete('backend');document.body.insertAdjacentHTML('afterbegin',`<div class="offline-banner local-banner" role="note">โหมดต้นแบบออฟไลน์ · ข้อมูลเก็บเฉพาะเครื่องนี้ ไม่มีสมาชิก <a class="text-button" href="${esc(u.href)}">เปิดโหมดสมาชิก</a></div>`);}
route=location.hash.slice(1)||'feed';decorateIcons();render();
